[package]
name = "brainrust"
version = "0.1.0"
authors = ["mcncm <mcnallychristopherm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.7.8"
termion = "1.5.4"